When last 6 chars of blame starts with -2 oc command fails
error in a openshift-client :
  error: unknown shorthand flag: '2' in -2s0iu
  See 'oc create secret generic --help' for usage.

Fixes: 86d319bf ("add test for reconciling secret of apicast custom policy")