freeze auth0-python <5.0.0 and widgetastic-core <2.0.0
updating to those versions results with tracebacks on ui tests:
E   ImportError: cannot import name 'auth0' from 'auth0.management' (.../site-packages/auth0/management/__init__.py)
E   ImportError: cannot import name 'UnexpectedAlertPresentException' from 'widgetastic.exceptions' (.../site-packages/widgetastic/exceptions.py)